const products = [
  {
    id: 1,
    name: "Crispy  Chicken Burguer",
    price: 35,
    rate: "100%",
    image: "../Images/burguer5.jpg",
    categories: ["Top Choices", "New Arrivals"],
    subCategories: ["Burguers"],
    type: ["fa-solid fa-drumstick-bite", "fa-solid fa-pepper-hot"],
  },
  {
    id: 2,
    name: "Beef On Sticks",
    price: 78,
    rate: "98%",
    image: "../Images/steak4.jpg",
    categories: ["Top Choices"],
    type: ["fa-solid fa-solid fa-bacon"],
    subCategories: ["Steak"],
  },
  {
    id: 3,
    name: "Sunshine Fish Fillets",
    price: 108,
    rate: "100%",
    image: "../Images/fish2.jpg",
    categories: ["Top Choices"],
    subCategories: ["Seafood"],
    type: ["fa-solid fa-fish"],
  },
  {
    id: 4,
    name: "36 Flavors of Kyoto",
    price: 250,
    rate: "100%",
    image: "../Images/sushi1.jpg",
    categories: ["Top Choices"],
    subCategories: ["Sushi"],
    type: ["fa-solid fa-cubes-stacked"],
  },
  {
    id: 5,
    name: "Beef  & Roasted Potatos",
    price: 95,
    rate: "90%",
    image: "../Images/steak5.jpg",
    categories: ["Top Choices"],
    subCategories: ["Steak"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 6,
    name: "Mistery Avocado Pizza",
    price: 85,
    rate: "100%",
    image: "../Images/pizza2.jpg",
    categories: ["Top Choices", "New Arrivals"],
    subCategories: ["Pizza"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 7,
    name: "12 Piece Sushi",
    price: 95,
    rate: "100%",
    image: "../Images/categorySection13.jpg",
    categories: ["Top Choices"],
    subCategories: ["Sushi"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 8,
    name: "Rainbow BBQ Burguer",
    price: 75,
    rate: "100%",
    image: "../Images/burguer8.jpg",
    categories: ["Top Choices", "New Arrivals"],
    subCategories: ["Burguers"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 9,
    name: "Special Tiger Shrimps",
    price: 150,
    rate: "97%",
    image: "../Images/fish3.jpg",
    categories: ["Top Choices"],
    subCategories: ["Seafood"],
    type: ["fa-solid fa-drumstick-bite", "fa-solid fa-pepper-hot"],
  },
  {
    id: 10,
    name: "Fried Chicken Bucket",
    price: 125,
    rate: "100%",
    image: "../Images/chicken3.jpg",
    categories: ["Top Choices", "New Arrivals"],
    subCategories: ["Burguers"],
    type: ["fa-solid fa-drumstick-bite", "fa-solid fa-pepper-hot"],
  },
  {
    id: 11,
    name: "Greek Chicken Burguer",
    price: 40,
    rate: "85%",
    image: "../Images/burguer10.jpg",
    categories: [],
    subCategories: ["Burguers"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 12,
    name: "Pinkakoladas",
    price: 45,
    rate: "90%",
    image: "../Images/categorySection4.jpg",
    categories: ["Top Choices"],
    subCategories: ["Cocktails"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 13,
    name: "Sweet Salmon Bulie",
    price: 82,
    rate: "92%",
    image: "../Images/fish5.jpg",
    categories: ["Top Choices", "New Arrivals"],
    subCategories: ["Seafood"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 14,
    name: "10 Stripes Beefs",
    price: 100,
    rate: "98%",
    image: "../Images/categorySection11.jpg",
    categories: ["Top Choices"],
    subCategories: ["Steak"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 15,
    name: "Smoked Ribs",
    price: 200,
    rate: "100%",
    image: "../Images/meat9.jpg",
    categories: ["Top Choices", "New Arrivals"],
    subCategories: ["Steak"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 16,
    name: "Pork Kyoto Ramen",
    price: 95,
    rate: "100%",
    image: "../Images/meat11.jpg",
    categories: ["Top Choices"],
    subCategories: ["Steak"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 17,
    name: "Mix Ratattouie",
    price: 75,
    rate: "94%",
    image: "../Images/steak2.jpg",
    categories: ["Top Choices", "New Arrivals"],
    subCategories: ["Steak", "Seafood"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 18,
    name: "Potato Shroomed",
    price: 40,
    rate: "100%",
    image: "../Images/mexican.jpg",
    categories: ["Top Choices", "New Arrivals"],
    subCategories: ["Steak", "Burguers", "Seafood", "HotDogs"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 19,
    name: "New York Burguer",
    price: 78,
    rate: "99%",
    image: "../Images/burguer15.jpg",
    categories: ["Top Choices", "New Arrivals"],
    subCategories: ["Burguer"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 20,
    name: "Hawatinni",
    price: 58,
    rate: "100%",
    image: "../Images/categorySection6.jpg",
    categories: ["Top Choices", "New Arrivals"],
    subCategories: ["Cocktails"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 21,
    name: "Seasoned Beefs",
    price: 82,
    rate: "92%",
    image: "../Images/categorySection9.jpg",
    categories: ["Top Choices", "New Arrivals"],
    subCategories: ["Steak"],
    type: ["fa-solid fa-cheese", "fa-solid fa-seedling"]
  },
  {
    id: 22,
    name: "Thai Meat Kadai",
    price: 70,
    rate: "100%",
    image: "../Images/meat10.jpg",
    categories: ["Top Choices", "New Arrivals"],
    subCategories: ["Steak"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 23,
    name: "Tuna Fillet & Kuskus",
    price: 80,
    rate: "98%",
    image: "../Images/categorySection5.jpg",
    categories: ["Top Choices", "New Arrivals"],
    subCategories: ["Seafood"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 24,
    name: "Earthly Green Pizza",
    price: 78,
    rate: "100%",
    image: "../Images/pizza3.jpg",
    categories: ["Top Choices"],
    subCategories: ["Pizza"],
    type: ["fa-solid fa-seedling", "fa-solid fa-lemon","fa-solid fa-pepper-hot"]
  },
  {
    id: 25,
    name: "Turkey Pizza",
    price: 78,
    rate: "100%",
    image: "../Images/pizza3.jpg",
    categories: ["Top Choices"],
    subCategories: ["Seafood"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 26,
    name: "Paella Shrimp",
    price: 135,
    rate: "100%",
    image: "../Images/seafood8.jpg",
    categories: ["Top Choices"],
    subCategories: ["Seafood"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 27,
    name: "Spaguetti Creamy Seafood",
    price: 94,
    rate: "98%",
    image: "../Images/seafood1.jpg",
    categories: ["Top Choices", "New Arrivals"],
    subCategories: ["Seafood"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 28,
    name: "In Your Face",
    price: 240,
    rate: "100%",
    image: "../Images/steak1.jpg",
    categories: ["Top Choices"],
    subCategories: ["Steak"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 29,
    name: "Crab Xl Burguer",
    price: 94,
    rate: "98%",
    image: "../Images/burguer10.jpg",
    categories: ["Top Choices", "New Arrivals"],
    subCategories: ["Burguer", "Seafood"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 30,
    name: "12 Piece Chicken",
    price: 85,
    rate: "100%",
    image: "../Images/chicken4.jpg",
    categories: ["Top Choices"],
    subCategories: ["Steak"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 31,
    name: "Tropicana",
    price: 58,
    rate: "98%",
    image: "../Images/categorySection16.jpg",
    categories: ["Top Choices"],
    subCategories: ["Cocktails"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 32,
    name: "Fruits of the Sea",
    price: 205,
    rate: "100%",
    image: "../Images/seafood10.jpg",
    categories: ["Top Choices", "New Arrivals"],
    subCategories: ["Seafood"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 33,
    name: "Red Caipora",
    price: 35,
    rate: "100%",
    image: "../Images/categorySection10.jpg",
    categories: ["Top Choices", "New Arrivals"],
    subCategories: ["Cocktails"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 34,
    name: "Pizza of Earthly Delights",
    price: 95,
    rate: "98%",
    image: "../Images/pizza9.jpg",
    categories: ["New Arrivals"],
    subCategories: ["Pizza"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 35,
    name: "Shrimp Rice Alfonse",
    price: 100,
    rate: "100%",
    image: "../Images/seafood6.jpg",
    categories: ["New Arrivals"],
    subCategories: ["Seafood"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 36,
    name: "Smoked Ribs Combo",
    price: 140,
    rate: "100%",
    image: "../Images/meat9.jpg",
    categories: ["New Arrivals"],
    subCategories: ["Steak"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 37,
    name: "Flavors of Kyoto",
    price: 150,
    rate: "100%",
    image: "../Images/sushi2.jpg",
    categories: ["New Arrivals"],
    subCategories: ["Sushi"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 38,
    name: "Fried Chicken 35 Tray",
    price: 140,
    rate: "100%",
    image: "../Images/chicken2.jpg",
    categories: ["New Arrivals"],
    subCategories: ["Chicken"],
    type: ["fa-solid fa-drumstick-bite", "fa-solid seedling", "fa-solid fa-pepper-hot"]
  },
  {
    id: 37,
    name: "Little Havana Burguer",
    price: 65,
    rate: "98%",
    image: "../Images/burger2.jpg",
    categories: ["Burguer"],
    subCategories: ["Sushi"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 38,
    name: "Florida Burguer",
    price: 70,
    rate: "100%",
    image: "../Images/burguer14.jpg",
    categories: ["New Arrivals"],
    subCategories: ["Burguer"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 39,
    name: "Texas Double Decker BBQ",
    price: 120,
    rate: "100%",
    image: "../Images/burguer14.jpg",
    categories: ["New Arrivals"],
    subCategories: ["Burguer"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 40,
    name: "Chicken Fillet",
    price: 82,
    rate: "100%",
    image: "../Images/chicken1.jpg",
    categories: [],
    subCategories: ["Chicken"],
    type: ["fa-solid fa-drumstick-bite", ]
  },
  {
    id: 41,
    name: "Something Chilli",
    price: 75,
    rate: "100%",
    image: "../Images/pizza1.jpg",
    categories: [],
    subCategories: ["Pizza"],
    type: ["fa-solid fa-seedling", "fa-solid fa-lemon","fa-solid fa-pepper-hot","fa-solid fa-pizza-slice"]
  },
  {
    id: 42,
    name: "Old School",
    price: 70,
    rate: "86%",
    image: "../Images/pizza5.jpg",
    categories: [],
    subCategories: ["Pizza"],
    type: ["fa-solid fa-seedling", "fa-solid fa-lemon","fa-solid fa-pizza-slice"]
  },
  {
    id: 43,
    name: "Italiana",
    price: 80,
    rate: "86%",
    image: "../Images/pizza8.jpg",
    categories: [],
    subCategories: ["Pizza"],
    type: ["fa-solid fa-seedling", "fa-solid fa-lemon","fa-solid fa-pizza-slice"]
  },
  {
    id: 44,
    name: "XL 6 Seasons",
    price: 100,
    rate: "100%",
    image: "../Images/pizza6.jpg",
    categories: [],
    subCategories: ["Pizza"],
    type: ["fa-solid fa-drumstick-bite", "fa-solid fa-pepper-hot", "fa-solid fa-fish","fa-solid fa-pizza-slice","fa-solid fa-bacon", "fa-solid fa-shrimp", "fa-solid fa-cheese"]
  },
  {
    id: 45,
    name: "Juicy Turkey Burguer",
    price: 50,
    rate: "90%",
    image: "../Images/burguer6.jpg",
    categories: [],
    subCategories: ["Burguer"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 46,
    name: "Spicy Burguer",
    price: 45,
    rate: "90%",
    image: "../Images/burguer4.jpg",
    categories: [],
    subCategories: ["Burguer"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 47,
    name: "HammyBurguer",
    price: 62,
    rate: "95%",
    image: "../Images/burguer7.jpg",
    categories: [],
    subCategories: ["Burguer"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 48,
    name: "20 Piece Otanawa",
    price: 115,
    rate: "100%",
    image: "../Images/categorySection3.jpg",
    categories: [],
    subCategories: ["Sushi"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 49,
    name: "8 Piece Mejin",
    price: 78,
    rate: "90%",
    image: "../Images/categorySection12.jpg",
    categories: [],
    subCategories: ["Sushi"],
    type: ["fa-solid fa-drumstick-bite"]
  },
  {
    id: 50,
    name: "Chicken Muai Thai",
    price: 72,
    rate: "80%",
    image: "../Images/chicken5.jpg",
    categories: [],
    subCategories: ["Chicken"],
    type: ["fa-solid fa-seedling, fa-solid fa-chicken, fa-solid fa-carrot, fa-solid fa-pepper-hot, fa-solid fa-bacon"]
  },
  {
    id: 51,
    name: "Zambeziana Chicken",
    price: 78,
    rate: "95%",
    image: "../Images/chicken6.jpg",
    categories: [],
    subCategories: ["Chicken"],
    type: ["fa-solid fa-seedling, fa-solid fa-chicken"]
  },
  {
    id: 52,
    name: "One Piece",
    price: 70,
    rate: "95%",
    image: "../Images/chicken7.jpg",
    categories: [],
    subCategories: ["Chicken"],
    type: ["fa-solid fa-seedling, fa-solid fa-chicken, fa-solid fa-pepper-hot","fa-solid fa-bowl-food"]
  },
  {
    id: 53,
    name: " Salad",
    price: 80,
    rate: "80%",
    image: "../Images/chicken8.jpg",
    categories: [],
    subCategories: ["Chicken"],
    type: ["fa-solid fa-seedling, fa-solid fa-chicken"]
  },
  {
    id: 54,
    name: "Tropical Panado",
    price: 92,
    rate: "98%",
    image: "../Images/chicken9.jpg",
    categories: [],
    subCategories: ["Chicken"],
    type: ["fa-solid fa-seedling, fa-solid fa-chicken"]
  },
  {
    id: 55,
    name: "Nachos Machos",
    price: 70,
    rate: "100%",
    image: "../Images/cocktail6.jpg",
    categories: [],
    subCategories: ["New Arrivals"],
    type: ["fa-solid fa-seedling, fa-solid fa-pepper-hot, fa-solid fa-cheese"]
  },
  {
    id: 56,
    name: "Caipooora",
    price: 35,
    rate: "100%",
    image: "../Images/cocktail.jpg",
    categories: [],
    subCategories: ["Drinks"],
    type: ["fa-solid fa-cup'straw"]
  },
  {
    id: 57,
    name: "Purple Sundown",
    price: 45,
    rate: "100%",
    image: "../Images/cocktail2.jpg",
    categories: [],
    subCategories: ["Drinks"],
    type: ["fa-solid fa-cup-straw"]
  },
  {
    id: 58,
    name: "Blue Paradise",
    price: 40,
    rate: "95%",
    image: "../Images/cocktail3.jpg",
    categories: [],
    subCategories: ["Drinks"],
    type: ["fa-solid fa-cup-straw"]
  },
  {
    id: 59,
    name: "Tropical Mix",
    price: 50,
    rate: "100%",
    image: "../Images/cocktail4.jpg",
    categories: [],
    subCategories: ["Drinks"],
    type: ["fa-solid fa-cup-straw"]
  },
  {
    id: 60,
    name: "Miami Burguer",
    price: 72,
    rate: "95%",
    image: "../Images/burger1.jpg",
    categories: [],
    subCategories: ["Burguer"],
    type: ["fa-solid fa-burger, fa-solid fa-seedling, fa-solid fa-cheese"]
  },
  {
    id: 61,
    name: "Raspeberry Punch",
    price: 50,
    rate: "100%",
    image: "../Images/cocktail5.jpg",
    categories: [],
    subCategories: ["Drinks"],
    type: ["fa-solid fa-cup-straw"]
  },
  {
    id: 62,
    name: "Water",
    price: 25,
    rate: "95%",
    image: "../Images/drink2.jpg",
    categories: [],
    subCategories: ["Drinks"],
    type: ["fa-solid fa-cup"]
  },
  {
    id: 63,
    name: "Sodas",
    price: 30,
    rate: "100%",
    image: "../Images/drink4.jpg",
    categories: [],
    subCategories: ["Drinks"],
    type: ["fa-solid fa-cup-straw"]
  },
  {
    id: 65,
    name: "Red Bull",
    price: 40,
    rate: "100%",
    image: "../Images/drink.jpg",
    categories: [],
    subCategories: ["Drinks"],
    type: ["fa-solid fa-cup-straw"]
  },
  {
    id: 66,
    name: "Earthly Tuna ",
    price: 67,
    rate: "100%",
    image: "../Images/seafood10.jpg",
    categories: [],
    subCategories: ["Drinks"],
    type: ["fa-solid fa-seedling, fa-solid fa-fish"]
  },
  {
    id: 67,
    name: "Jack Daniels Honey",
    price: 350,
    rate: "100%",
    image: "../Images/whiskey.jpg",
    categories: [],
    subCategories: ["Drinks"],
    type: ["fa-solid fa-cup"]
  },
  {
    id: 68,
    name: "BarterHouse Orphan Barrel",
    price: 430,
    rate: "100%",
    image: "../Images/whiskey2.jpg",
    categories: [],
    subCategories: ["Drinks"],
    type: ["fa-solid fa-cup"]
  },
  {
    id: 69,
    name: "Jameson Tripple Distilled",
    price: 280,
    rate: "100%",
    image: "../Images/whiskey3.jpg",
    categories: [],
    subCategories: ["Drinks"],
    type: ["fa-solid fa-cup"]
  },
  {
    id: 70,
    name: "Vistalba",
    price: 125,
    rate: "100%",
    image: "../Images/wine.jpg",
    categories: [],
    subCategories: ["Drinks"],
    type: ["fa-solid fa-cup"]
  },
  {
    id: 71,
    name: "Rasteau",
    price: 170,
    rate: "100%",
    image: "../Images/wine2.jpg",
    categories: [],
    subCategories: ["Drinks"],
    type: ["fa-solid fa-cup"]
  },
  {
    id: 72,
    name: "Roche Mazet Chardonay",
    price: 140,
    rate: "100%",
    image: "../Images/wine3.jpg",
    categories: [],
    subCategories: ["Drinks"],
    type: ["fa-solid fa-cup"]
  },
  {
    id: 73,
    name: "Borsao",
    price: 140,
    rate: "100%",
    image: "../Images/wine4.jpg",
    categories: [],
    subCategories: ["Drinks"],
    type: ["fa-solid fa-cup"]
  },
  {
    id: 74,
    name: "Sauvignon Blanc",
    price: 132,
    rate: "100%",
    image: "../Images/wine5.jpg",
    categories: [],
    subCategories: ["Drinks"],
    type: ["fa-solid fa-cup"]
  },
  {
    id: 75,
    name: "Cheesy Burguer",
    price: 82,
    rate: "100%",
    image: "../Images/burguer13.jpg",
    categories: [],
    subCategories: ["Drinks"],
    type: ["fa-solid fa-burger, fa-solid fa-cheese"]
  },
];
